### ISSUE TITLE
`Edit Syllable text` box quirk

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Neon2#1082] opened 2023-08-07 08:35 UTC
I don't know how to name this issue, but the steps to reproduce it should explain it:

- In any given folio in Neon, open the `Edit syllable text` box. You can do it by clicking on a syllable or using the keyboard shortcut, it works both ways.
- Erase the syllable already in there.
- Press the `up` arrow key.
- The syllable "it" will appear in a smaller font. I've tried in multiple folios and it always seems to be "it." If you press the `Enter` key, the "it" suggestion will be selected.

This isn't at all a huge problem; it's just intriguing!

**Comment by annamorphism** [comment] 2023-08-07 16:56
I can't seem to reproduce this (working with the sample files) but it sounds weird and I want to see it!
I wonder why it happens for you but not me..???

**Comment by JoyfulGen** [comment] 2023-08-08 06:42
@annamorphism are you using Firefox? I've just tried it and I'm not seeing it on Firefox either, only Chrome. It looks like this:

https://github.com/DDMAL/Neon/assets/83373378/f4e1bac3-75b8-4480-ac7d-e1bed90ce6e9

**Comment by yinanazhou** [comment] 2023-08-10 20:09
Hi @JoyfulGen, I cannot reproduce this error in Chrome. Does it happen for any bbox?

**Comment by JoyfulGen** [comment] 2023-08-11 06:05
@yinanazhou yes, any bbox and any folio, from what I can tell so far.

**Comment by yinanazhou** [comment] 2024-06-03 16:49
Hi @JoyfulGen, is this still happening?

**Comment by JoyfulGen** [comment] 2024-06-04 15:12
As a matter of fact, it is! Fun fact though: the syllable that appears for me now is "hai." I use "hai" fairly often when I find a bug and I need a recognizable syllable, so I can't tell you when this happened...

https://github.com/DDMAL/Neon/assets/83373378/ea8f448b-bb5a-4995-b98d-31c9c3889b80

**Comment by yinanazhou** [comment] 2024-06-04 15:36
@JoyfulGen In this case, it might be your chrome settings that it autofills for text field. Could you please try disable autofill in chrome and see if it still happens?

**Comment by JoyfulGen** [comment] 2024-06-05 08:37
@yinanazhou it's gone! Magic

**Comment by yinanazhou** [comment] 2024-06-05 13:41
Glad to hear that! I will thus close this issue.

**Closed as completed by yinanazhou** 2024-06-05 13:41 UTC
